[package]
name = "rs_merkle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"

# standard crate data is left out
[dev-dependencies]
rayon = "1.5.1"
