name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run tests
        run: cargo test
      - shell: bash
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "$CARGO_TOKEN" && cargo publish
